### ISSUE TITLE
ASX?

### ISSUE THREAD

**Issue by meyskens** [Innovate-Technologies/Cast#10]
Check if Windows Media Player supports m3u. If not we shall add asx links to Cast.

**Comment by ncborges** [comment]
It doesn't support. I've been looking into this but use VLC to play stream with m3u extension

**Comment by meyskens** [comment]
That saves me a Windows 10 vm, thanks. Will be added soon.

**Comment by ncborges** [comment]
It i'll be so much apreciated. Thnaks so much.

**Comment by meyskens** [comment]
For own reference https://en.wikipedia.org/wiki/Advanced_Stream_Redirector

**Comment by meyskens** [comment]
See #11
