### ISSUE TITLE
SSL on 443 ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by inetactief** [innovate-technologies/Cast#127]
Hi,

I try to enabled ssl on port 443 We use the pem and key file wat work for Icecast and directadmin.

{
    "httpPort": 80,
    "httpsPort": 443,
    "httpsCert": "/etc/ssl/x.somename.nl.pem",
    "httpsKey": "/etc/ssl/x.somename.nl.key",

On the screen, client side he say ERR_SSL_PROTOCOL_ERROR. 

Normal for other services we have 3 files and 2 file for use..
.csr
.key
.pem

Hope somebody can help me.

**Comment by meyskens** [comment]
StackOvervlow to the rescue: https://stackoverflow.com/questions/41892547/nodejs-https-server-returning-err-ssl-protocol-error-using-express#42775630

**Comment by meyskens** [comment]
Which version of node.js is being used?

**Comment by inetactief** [comment]
node -v
v8.11.3

**Comment by meyskens** [comment]
I disabled http2 in 0296d741151becf3a5c9a34a932bb51466f6fcb3
It seems the API changed over time causing issues

**Comment by inetactief** [comment]
But what does that mean? its correct that https do not work?

**Comment by meyskens** [comment]
http2 was broken, it should work again since the above commit

**Comment by inetactief** [comment]
Okay i change the file intern/HTTP/server.js to https and it works. 
Only when i click on play the green icon is gone. The stream is not https.

**Comment by inetactief** [comment]
So again pull in /Cast: 
git clone https://github.com/Innovate-Technologies/Cast.git
