### ISSUE TITLE
Release 1.1.1

### ISSUE THREAD

**Issue by inetactief** [innovate-technologies/Cast#129]
I use on sunday git clone https://github.com/Innovate-Technologies/Cast.git 

When i start i see version 1.0 it that correct?

node server.js
Cast 1.0

**Comment by meyskens** [comment]
https://github.com/innovate-technologies/Cast/blame/0296d741151becf3a5c9a34a932bb51466f6fcb3/server.js#L6

This is hardcoded in there, last changed 2 years ago

**Comment by inetactief** [comment]
How can we update the code in the future?

**Comment by meyskens** [comment]
If you want you can change that code in `server.js`
