### ISSUE TITLE
Example of live input?

### ISSUE THREAD

**Issue by inetactief** [innovate-technologies/Cast#143]
Hi, 
Is there a example of a config for connecting from a live encoder to Cast using ice of sc type?
Now there is example of relay. That works fine.

**Comment by meyskens** [comment]
The sample config already contains 2 live streams!  Nore info: https://cast.readme.io/docs/configuring-cast#section-input

**Comment by inetactief** [comment]
Okay.. it's not clear, so :
Input part is is for type and port number for the encoder.
"input": {
        "SHOUTcast": 8000,
        "Icecast": 9000
    },

And encoder setting are for Ice and type SHOUTcast encoder : 

  }, {
        "stream": "live",
        "password": "live",
        "primary": true
    }]

**Comment by meyskens** [comment]
"input" is the port Cast will listen on for these connections, the password in stream is the password needed

**Comment by inetactief** [comment]
Thanks!
