### ISSUE TITLE
IPv6 and Cast

### ISSUE THREAD

**Issue by inetactief** [innovate-technologies/Cast#145]
Hi, 

How can use IPv6 and Cast?

**Comment by meyskens** [comment]
I think this answers the question:
```
user@maartje-xps13 ~/I/Cast> netstat -tulpn
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::9000                 :::*                    LISTEN      525/node
tcp6       0      0 :::8080                 :::*                    LISTEN      525/node
tcp6       0      0 :::8000                 :::*                    LISTEN      525/node
tcp6       0      0 :::8001                 :::*                    LISTEN      525/node
```

**Comment by inetactief** [comment]
Okay great!.. and how to set a IPv6 binding address in the config?

**Comment by meyskens** [comment]
You don't, Node.js autobinds on IPv6. I just used the sample config but with port 80 since i run it as an unprivileged user.

**Comment by inetactief** [comment]
Okay, when the server use multi IPv6 address and we want run more Cast accounts on one server on the same port?

**Comment by meyskens** [comment]
That would require a code change in https://github.com/innovate-technologies/Cast/blob/master/intern/HTTP/server.js#L17 to include a host (https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback)
