### ISSUE TITLE
How to use control and Cast-Statistics

### ISSUE THREAD

**Issue by inetactief** [innovate-technologies/Cast#150]
Hi,

Looks like Cast is very good product.  Only we like to have a webinterface to see some listener infromation. Like stream starts of the day, week and current listeners.  

How can we use that?

**Comment by meyskens** [comment]
Control relies on ITFrame as backend. Here starts the trouble: ITFrame (and in some extend Control) are specifically built around our billing and legacy infrastructure. With open sourcing ITFrame (cast and control were always open source) we had the vision for a standalone ITFrame-CE. We currently don’t have enough dev hours to get our own features built so we never completed this work. 

PRs welcome.

**Comment by inetactief** [comment]
okay, I understand. If there is no management interface, this product will not be appreciated by users no matter how good it is.
I have seen the api and the outputs, with php I could show something. I hope in the future there is something as simple as like admin interface show listeners. 
When there is xml output same like ice we can grep the information on our database and then it is icecast compatible! :+1:

**Comment by meyskens** [comment]
Do you mean this? https://github.com/innovate-technologies/Cast/blob/master/intern/HTTP/apps/icecast.js#L3

**Comment by meyskens** [comment]
Also to our vision a management interface is not right be be part of the Cast codebase. Should you want one Pillar 0 might be the answer: Cast has a plugin system you can use to add your own HTTP request handlers

**Comment by inetactief** [comment]
We use in Icecast : admin/stats xml and admin/listclients?mount=/live output to feed our db.

**Comment by meyskens** [comment]
I have created #152 to add the admin apis from icecast.
