### ISSUE TITLE
How to start a second stream

### ISSUE THREAD

**Issue by inetactief** [innovate-technologies/Cast#178]
Hi,

I like to start a second stream on same server where running on Cast (other ip and dns name). How to do that?
cp config.json to a config2.json ? 
And gen i set  a limit for slots?

Best regards,
Michel

**Comment by inetactief** [comment]
I start the server now by node server.js > /dev/null 2>&1 & 
But my new config is  config2.json

**Comment by inetactief** [comment]
When i run server.js config2.json > /dev/null 2>&1 &
Hey run this config on both ip's. So i can not start the first config on the same way. So i can not start the second. How can i make this config work for on IP?

Here i my config:
{
    "httpPort": 80,
    "httpsPort": 443,
    "httpsCert": "/etc/ssl/x.live-streams.nl.pem",
    "httpsKey": "/etc/ssl/x.live-streams.nl.key",
    "hostname": "https://xxx.live-streams.nl",
    "apikey":"xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "trustProxy":false,

  "hls": true,
    "dash": true,


    "input": {
        "SHOUTcast": 8000
    },

    "directories":{
        "Icecast":[]
    },

    "streams": [{
        "stream": "192kbps",
        "password": "password"
    }, {
        "stream": "live",
        "password": "xxxxx",
        "primary": true
    }]

}

**Comment by meyskens** [comment]
Currently Cast does not support binding on a specific address, since we only run cast inside containerized infrastructure we never had the need

Issue is described in https://github.com/innovate-technologies/Cast/issues/179

Happy Hacktoberfest

**Comment by inetactief** [comment]
okay I understand
