### ISSUE TITLE
add static code analysis?

### ISSUE THREAD

**Issue by NaanProphet** [innovate-technologies/Cast#190]
Hi!

I was wondering if we might analyze Cast with SonarQube's JS rule engine. It's free for open source projects like Cast: https://sonarcloud.io/about/sq

The sonar-project.properties file would look something like (what I'm using locally):

```
# must be unique in a given SonarQube instance
sonar.projectKey=innovate-technologies:cast
sonar.projectVersion=1.1.2
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/bower_components/**
sonar.sourceEncoding=UTF-8
```

If you'd like a hand/more info, I'd be more than happy to help!

**Comment by meyskens** [comment]
Thanks for the suggestion: I added it in https://github.com/innovate-technologies/Cast/pull/201 to test

**Comment by meyskens** [comment]
I have added it to test it further. My first impressions are that I get a ton of false positives, especially in ES6 code.

**Comment by NaanProphet** [comment]
Cool! This looks really exciting https://sonarcloud.io/dashboard?id=innovate-technologies%3Acast

You might be able to curate the quality profile by disabling certain stylistic rules to reduce the false positives. I really like using SonarQube for my own personal projects, so let me know if you need a hand!

**Comment by meyskens** [comment]
Will try to disable style. For style I plan to test the [source{d} style analyzer](https://github.com/src-d/style-analyzer) with [lookout](https://github.com/src-d/lookout)

**Comment by NaanProphet** [comment]
A year later, it's awesome to see this project is still being analyzed with SonarQube and is passing :) 
![image](https://user-images.githubusercontent.com/2568736/67241721-f3080d00-f421-11e9-87a4-3a099bdc5c7e.png)

Thanks for implementing this suggestion 👍
