### ISSUE TITLE
Hide listener count

### ISSUE THREAD

**Issue by meyskens** [Innovate-Technologies/Cast#3]
Some people seem to prefer to hide the listener count. We'll add this to the configuration.

**Comment by meyskens** [comment]
Now the big question: Hide it in the API? And what to show in the SHOUTcast and Icecast one?

**Comment by leoetlino** [comment]
Yes, should likely be hidden in the *public* APIs too, and for the compatibility APIs, set to 99999 (or any value that will probably not be reached normally)? For the private ones, I'd suggest keeping it.

**Comment by meyskens** [comment]
99999 can be, only the YP should stay 0 as you can and will get banned for faking these counts.

**Comment by meyskens** [comment]
See #29
