### ISSUE TITLE
Virtual DJ not Listen

### ISSUE THREAD

**Issue by Toso82** [innovate-technologies/Cast#52]
@meyskens  Hi i try to use cast with Virtual DJ. Virtual DJ connect well in all streams in config.json in console i don't have strange error. I see all good in web page stream and play button. But i listen notting.
In the web browser (Crome Canary) console in net section give me:

Request URL:http://localhost/streams/live
Request Method:GET
Status Code:404 Not Found
Remote Address:[::1]:80

No response data

**Comment by meyskens** [comment]
Any more info on the info used in Virtual DJ?

**Comment by Toso82** [comment]
more info what do you want ? 
Version 8.2 b3552

Protocol: ShoutCast   320Kbps
Url: 127.0.0.1
Server Port: 8000
Session Name: Live    Gener Session: Live

I try with and without  broutcastSoungInfo enable

**Comment by meyskens** [comment]
<img width="626" alt="schermafbeelding 2016-12-10 om 23 01 58" src="https://cloud.githubusercontent.com/assets/1625272/21076479/c30e4146-bf2c-11e6-9253-914179c564c9.png">
I did a test on a production server (1.0.5) and it works fine here.

**Comment by Toso82** [comment]
I don't now what do u use for streamming ? i try but not work i must try if its something strange in my pc or virtual dj

**Comment by Toso82** [comment]
I find the problem!!! The problem is when not use standard port 80 in configuration, I don't know but maybe some url don't have port try to verify and fix.

**Comment by Toso82** [comment]
@meyskens Sorry why close? You don't fix notthing.. There is a some error in host url inside code. Something i fix something no in my code now work with no standard port 80. I try to find why don't work. We don't listen outside my net.

**Comment by Toso82** [comment]
Notthing in code?? You try a local test with different default port ? Not work simply.
----------------------------------------------------------------------------------------------
icecast-yp.js (line 26) 

(This is not correct)

if (config.hostname.split(":").length === 3) { // if a non standard port is used
        hostname = config.hostname;
    } else if (config.httpPort === 0) { // if only serves over https
        hostname = config.hostname + ":" + config.httpsPort.toString()
    } else { // If both or only http, use http as some directories may have https issues
        hostname = config.hostname.replace("https://", "http://") + ":" + config.httpPort.toString()
    }

(This is correc)

 if (config.httpPort != 0) {
        hostname = config.hostname.concat((config.httpPort != 80) ? ":" + config.httpPort.toString() : "");
    }else if (config.httpPort === 0) { 
        hostname = config.hostname + ":" + config.httpsPort.toString()
    } else {
        hostname = config.hostname.replace("https://", "http://") + ":" + config.httpPort.toString()
    }

----------------------------------------------------------------------------------------------
front.js

Line 23 and 52

This is not correct where is the port reference?

hostname: config.hostname,

This is correct and there isn't condiction to https ports

 hostname: config.hostname.concat((config.httpPort != 80) ? ":" + config.httpPort : ""),

**Comment by meyskens** [comment]
Cast is assumed to be able to run behind a reverse proxy and assumes the hostname contains the correct port, however on that logic I'm not sure why i still used the http port in there

**Comment by Toso82** [comment]
@meyskens 
Ok if Cast assumed that port is in hostname there is no sense to has httpPort in config or in code. So i must have a reverse proxy to  translate all request to local ip. If it assumed this just to know. It could be 
advantage or disadvantage. Why not to do all inside component without reverce proxy?

**Comment by meyskens** [comment]
no, it is possible to run behind one but isn't obligated nor has advantages on a single installation.
Now I see why I did use the ports in the YP hook. If the port isn't 80 or 443 it has to be noted in the hostname, otherwise it still needs to add the port 80 to the hostname as some directories don't support URLs without  port number in it.

**Comment by Toso82** [comment]
@meyskens  Ok now work well inside and outside my net with the last fix thanks !!. I have a problem just with a client but i don't know why mmm your https://opencast.radioca.st/ send notthing to test if it is my problem.  There is no example of config.json of ITFrame? I see that use mongo db it is correct?

**Comment by meyskens** [comment]
https://github.com/innovate-technologies/ITFrame/blob/master/components/cast/database.js
does that help?

**Comment by Toso82** [comment]
No in ITFrame when lunch with npm app.js ? miss config.json there is example or i can find how create

**Comment by Toso82** [comment]
@meyskens  Any news of me i try the service on your service but i have the same insus websocket error and the sound is not clear and jump on SL Viewer

**Comment by meyskens** [comment]
If this is for our hosted service a support ticket is suggested.

**Comment by Toso82** [comment]
@meyskens Ok but this is the same error i send here there is something not perfect in component.

**Comment by meyskens** [comment]
`wss://opencast.radioca.st/socket.io/?EIO=3&transport=websocket&sid=7_TLTAlrY2MeLN6NAAIO`
If you're not on opencast.radioca.st, change your hostname.
If you are check your browser. That site is on a HTTP/2 supported server, HTTP/2 has no websocket support so it will only work ok HTTP/1.1

**Comment by Toso82** [comment]
@meyskens 
Sorry but i use you server and give the same arror:

VM272:35 WebSocket connection to 'wss://toso82.radioca.st/socket.io/?EIO=3&transport=websocket&sid=LJhUXk79Eij9xR18AAAE' failed: Error during WebSocket handshake: Unexpected response code: 400

I know that use HTTP/2.

And also why SL Viewer not listen well and in web browser this is perfect. I mean that there is something missing in shotcast protocol.

**Comment by meyskens** [comment]
Then that error is normal, socket.io has a few fallback modes to fix that. Is there any error? The SHOUTcast prototol (which is just a never ending download nothing fancy) shouldn't be the issue.

**Comment by Toso82** [comment]
Ok but why with SL Viewer sound jump and something glich or sound not clear? A big mistery!! :-(

**Comment by meyskens** [comment]
Sounds more like MP3 decoding issues

**Comment by Toso82** [comment]
In web is clear

**Comment by meyskens** [comment]
that is why it is decode and not encoding issues

**Comment by Toso82** [comment]
so means that shotcast process the mp3

**Comment by meyskens** [comment]
SHOUTcast/Icecast/... doesn't process the MP3 data, it just passes it along

**Comment by Toso82** [comment]
so what is the diffence in shotcast work well

**Comment by meyskens** [comment]
I have no idea. I need more details for that.

**Comment by Toso82** [comment]
I want to understand me to what is the problem.  Any Ideal to possibility to debug or how to find the problem. Because i know that there is a lot of people and possibility client to could use that service in SL. But it is not work use the other.

**Comment by meyskens** [comment]
Feel free to investigate and send a PR. For us this isn't a priority.

**Comment by leoetlino** [comment]
This is likely not our issue. If you have a reproducible case in a more mainstream, or even better, in an open-source player, feel free to open another issue.
Please note that this is not a support forum.
