### ISSUE TITLE
binary?

### ISSUE THREAD

**Issue by meyskens** [Innovate-Technologies/Cast#6]
Will we provide a static binary using [nexe](https://www.npmjs.com/package/nexe) for not very technical people to use?

**Comment by meyskens** [comment]
@leoetlino

**Comment by leoetlino** [comment]
It's a bit complex and some of our code will need to be changed to work (dynamic `require`s aren't supported, for example, and requires workarounds which make the code less readable).

Also, I think that people who don't know how to `git clone`, `npm i` and start the server won't know how to use the binary properly, configure Cast with a config file either. That is to say − most people who know how to get started don't need such a binary. So I'm not really convinced of its utility.

(PS: I watch the repo, so you don't need to mention me to send me a notification.)

**Comment by meyskens** [comment]
In some points I agree. My thing is if we want to push forward Cast and future OpenRadio protocols we need to make it accessible. As far as I know there are no dynamic requires in Cast. I will do a test later to see how much work it is.

**Comment by ethangates** [comment]
I agree with Léo. I don't think that there's that much logistical effort in it anyway and making changes to the code is time consuming. We can always work on developing this in future, after initial release.

**Comment by leoetlino** [comment]
Here is an example of a dynamic require (which is essential to Cast): [hooks/hooks.js#L28](https://github.com/Innovate-Technologies/Cast/blob/47641307cc52313a3df3808f8fcf37fd4c3f937f/hooks/hooks.js#L28)

We need to find something around that which doesn't hurt the readability or make the code too complex if we want to use nexe.

I do agree that this is more convenient for potential users but that's only **if** we implement it correctly.

**Comment by meyskens** [comment]
oh yeah hooks (now i remember)

**Comment by meyskens** [comment]
These are now available: https://github.com/Innovate-Technologies/Cast/releases/tag/1.0.0
